STEP2 fail

diff --git a/.github/workflows/Status-check.yaml b/.github/workflows/Status-check.yaml
--- a/.github/workflows/Status-check.yaml
+++ b/.github/workflows/Status-check.yaml
@@ -7,16 +7,24 @@ jobs:
         steps:
             - name: step 1
               run: sleep 20 
-            - name: run on failure
-              if: failure() # this step will run only if any of the previous steps in the job have failed
-              run: echo "This step runs only if any of the previous steps have failed"
+
+            - name: Step 2
+              id: step-2
+              run: exit 1
+              
+            - name: Runs on Failure
+              if: failure() && steps.step-2.conclusion == 'failure'
+              run: echo 'Step 2 has failed'
+            
             - name: run on success
             # this is not needed  cause its a default behaviour
               if: success() # this step will run only if all the previous steps in the job have succeeded
               run: echo "This step runs only if all the previous steps have succeeded"
+
             - name: run always
               if: always() # this step will run regardless of the outcome of the previous steps in the job and works if workflow is cancaled
               run: echo "This step runs regardless of the outcome of the previous steps in the job"
+
             - name: run when cancelled
               if: cancelled() # this step will run only if the workflow run is cancelled
               run: echo "This step runs only if the workflow run is cancelled"
